shell = "zsh"

# Templates for deferred loading
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# zsh-defer must be loaded first
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Completions - defer for faster startup
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

# Autosuggestions - DO NOT USE DEFER (causes infinite recursion)
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

# Syntax highlighting - fast-syntax-highlighting for better performance
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]
