[tools]
node = "lts"           # Node.js LTS version
python = "3.13"        # Python 3.13 (stable)
go = "latest"          # Latest Go version
ruby = "3.3"           # Ruby 3.3

# npm global packages
"npm:@anthropic-ai/claude-code" = "latest"  # Claude Code CLI
"npm:@google/gemini-cli" = "latest"         # Gemini CLI
"npm:@slidev/cli" = "latest"                # Slidev presentation tool
"npm:git-open" = "latest"                   # Open GitHub repo from terminal
"npm:ccusage" = "latest"                    # Claude Code usage tracker

[settings]
experimental = true
