# External dependencies managed by chezmoi
# These will be automatically downloaded/updated when running chezmoi apply

# Note: oh-my-zsh removed (not used, causes 1-3s startup delay)
# Powerlevel10k now installed standalone via run_once script

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

# Brewfile dependencies are now managed locally via run_onchange_install-packages.sh.tmpl