#!/bin/bash
# ==============================================================================
# macOS System Preferences (Auto-discovered)
# ==============================================================================
# This file was automatically generated by scripts/extract-macos-defaults.sh
#
# IMPORTANT: Review and customize this file before using it!
# - Remove settings you don't want to version control
# - Adjust values as needed
# - Add comments to explain non-obvious settings
# ==============================================================================

set -eufo pipefail

echo "🔧 Applying macOS system preferences..."


# ============================================================================
# Dock
# ============================================================================
defaults write com.apple.dock "expose-group-apps" -bool true
defaults write com.apple.dock "minimize-to-application" -bool true
defaults write com.apple.dock "mod-count" -int 2505
defaults write com.apple.dock "mru-spaces" -bool false
defaults write com.apple.dock "bundle-identifier" -string "com.1password.1password"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/1Password.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "1Password"
defaults write com.apple.dock "file-mod-date" -int 3843309148
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 244950124006999
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "company.thebrowser.Browser"
defaults write com.apple.dock "dock-extra" -bool true
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Arc.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Arc"
defaults write com.apple.dock "file-mod-date" -int 94102282472286
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 244950124006999
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.anthropic.claudefordesktop"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Claude.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Claude"
defaults write com.apple.dock "file-mod-date" -bool false
defaults write com.apple.dock "file-type" -bool true
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -bool false
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "org.alacritty"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Alacritty.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Alacritty"
defaults write com.apple.dock "file-mod-date" -int 77918845361162
defaults write com.apple.dock "file-type" -bool true
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 69466350149576
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.mitchellh.ghostty"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Ghostty.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Ghostty"
defaults write com.apple.dock "file-mod-date" -int 254175712399365
defaults write com.apple.dock "file-type" -bool true
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 244950124006999
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.microsoft.VSCode"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Visual%20Studio%20Code.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Visual Studio Code"
defaults write com.apple.dock "file-mod-date" -int 3842211800
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 99569775849715
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "md.obsidian"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Obsidian.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Obsidian"
defaults write com.apple.dock "file-mod-date" -int 81500828305482
defaults write com.apple.dock "file-type" -bool true
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 69466350149576
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "notion.id"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Notion.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Notion"
defaults write com.apple.dock "file-mod-date" -int 3816773624
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 264672587907805
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.cron.electron"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Notion%20Calendar.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Notion Calendar"
defaults write com.apple.dock "file-mod-date" -int 3842592570
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 41360084157565
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.tinyspeck.slackmacgap"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Slack.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Slack"
defaults write com.apple.dock "file-mod-date" -int 3831847594
defaults write com.apple.dock "file-type" -bool true
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 169543375932765
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.readdle.smartemail-Mac"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Spark.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Spark"
defaults write com.apple.dock "file-mod-date" -int 121843463341762
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 132065489316799
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.electron.dockerdesktop"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Docker.app/Contents/MacOS/Docker%20Desktop.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Docker Desktop"
defaults write com.apple.dock "file-mod-date" -int 3756993171
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 201029714375005
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.spotify.client"
defaults write com.apple.dock "dock-extra" -bool false
defaults write com.apple.dock "_CFURLString" -string "file:///Applications/Spotify.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Spotify"
defaults write com.apple.dock "file-mod-date" -int 144314744794076
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 160060095728667
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "bundle-identifier" -string "com.apple.AppStore"
defaults write com.apple.dock "dock-extra" -bool true
defaults write com.apple.dock "_CFURLString" -string "file:///System/Applications/App%20Store.app/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "App Store"
defaults write com.apple.dock "file-mod-date" -int 3841628612
defaults write com.apple.dock "file-type" -int 41
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 3841628612
defaults write com.apple.dock "tile-type" -string "file-tile"
defaults write com.apple.dock "_CFURLString" -string "file:///Users/ryosukematsushima/Library/CloudStorage/Dropbox/My%20Mac%20(RsM1MBP)/Downloads/"
defaults write com.apple.dock "_CFURLStringType" -int 15
defaults write com.apple.dock "file-label" -string "Downloads"
defaults write com.apple.dock "file-mod-date" -int 162271930438406
defaults write com.apple.dock "file-type" -int 2
defaults write com.apple.dock "is-beta" -bool false
defaults write com.apple.dock "parent-mod-date" -int 248905715765995
defaults write com.apple.dock "tile-type" -string "directory-tile"
defaults write com.apple.dock "show-process-indicators" -bool true
defaults write com.apple.dock "show-recents" -bool false
defaults write com.apple.dock "trash-full" -bool true
defaults write com.apple.dock "wvous-bl-corner" -bool true
defaults write com.apple.dock "wvous-bl-modifier" -int 1048576
defaults write com.apple.dock "wvous-br-corner" -int 14
defaults write com.apple.dock "wvous-br-modifier" -int 1048576

# ============================================================================
# Finder
# ============================================================================
defaults write com.apple.finder "FK_AppCentricShowSidebar" -bool true
defaults write com.apple.finder "FK_SidebarWidth" -int 154
defaults write com.apple.finder "FK_SidebarWidth2" -int 227
# TODO: Complex value for FXPreferencesWindow.Location - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
# TODO: Complex value for file-bookmark - requires manual handling
defaults write com.apple.finder "TB Display Mode" -int 2
defaults write com.apple.finder "TB Icon Size Mode" -bool true
defaults write com.apple.finder "TB Is Shown" -bool true
defaults write com.apple.finder "TB Size Mode" -bool true
defaults write com.apple.finder "NSWindow Frame NSNavPanelAutosaveName" -string "436 525 877 363 0 0 1680 1025"
defaults write com.apple.finder "NSWindow Frame NSSpellCheckerSubstitutionsPanel2" -string "692 407 440 137 0 0 1440 875"
defaults write com.apple.finder "PreferencesWindow.LastSelection" -string "GNRL"
# TODO: Complex value for ViewOptionsWindow.Location - requires manual handling
# TODO: Complex value for _FXInputMethodLocation - requires manual handling

# ============================================================================
# Global Preferences (Keyboard, Trackpad, etc.)
# ============================================================================
defaults write NSGlobalDomain "KB_DoubleQuoteOption" -string "\U201cabc\U201d"
defaults write NSGlobalDomain "KB_SingleQuoteOption" -string "\U2018abc\U2019"
defaults write NSGlobalDomain "KB_SpellingLanguageIsAutomatic" -bool true
# TODO: Complex value for _AKBAACertMarkerKey - requires manual handling
defaults write NSGlobalDomain "_HIHideMenuBar" -bool false
defaults write NSGlobalDomain "com.aone.keka.KekaFinderIntegration" -bool false
defaults write NSGlobalDomain "com.linguee.DeepLCopyTranslator.DeepLTranslatorFinderExt" -bool true
# TODO: Complex value for com.apple.gms.availability.accessNotGrantedUseCases - requires manual handling
# TODO: Complex value for com.apple.gms.availability.disabledUseCases - requires manual handling
# TODO: Complex value for com.apple.gms.availability.disallowedUseCases - requires manual handling
# TODO: Complex value for com.apple.gms.availability.essentialAssetReadiness - requires manual handling
# TODO: Complex value for com.apple.gms.availability.key - requires manual handling
# TODO: Complex value for com.apple.gms.availability.useCasesWhoseAssetsAreOutOfStorage - requires manual handling
# TODO: Complex value for com.apple.gms.availability.useCasesWhoseAssetsNotReady - requires manual handling
defaults write NSGlobalDomain "com.apple.mouse.doubleClickThreshold" -float 0.2
defaults write NSGlobalDomain "com.apple.mouse.scaling" -int 3
defaults write NSGlobalDomain "com.apple.mouse.tapBehavior" -bool true
defaults write NSGlobalDomain "com.apple.sound.beep.flash" -bool false
defaults write NSGlobalDomain "com.apple.sound.uiaudio.enabled" -bool true
defaults write NSGlobalDomain "com.apple.springing.delay" -float 0.8
defaults write NSGlobalDomain "com.apple.springing.enabled" -bool true
defaults write NSGlobalDomain "com.apple.trackpad.forceClick" -bool true
defaults write NSGlobalDomain "com.apple.trackpad.scaling" -int 3
defaults write NSGlobalDomain "com.apple.trackpad.scrolling" -float 0.5881999999999999

# ============================================================================
# Screenshots
# ============================================================================
defaults write com.apple.screencapture "disable-shadow" -bool false
defaults write com.apple.screencapture "last-analytics-stamp" -float 783447026.217998
defaults write com.apple.screencapture "last-selection-display" -bool false
defaults write com.apple.screencapture "location-last" -string "~/Pictures"
defaults write com.apple.screencapture "show-thumbnail" -bool false

# ==============================================================================
# Restart Affected Applications
# ==============================================================================
echo "🔄 Restarting affected applications..."

for app in \
    "Dock" \
    "Finder" \
    "SystemUIServer" \
    "Safari"; do
    killall "${app}" &>/dev/null || true
done

echo "✅ macOS system preferences applied successfully"
echo ""
echo "⚠️  Some changes may require a logout/restart to take full effect"
