name: Dotfiles CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew dependencies
        run: |
          brew install chezmoi hyperfine

      - name: Validate chezmoi configuration
        run: |
          chezmoi init --dry-run --verbose

      - name: Test chezmoi apply (dry-run)
        run: |
          chezmoi apply --dry-run --verbose

      - name: Benchmark zsh startup time
        run: |
          # Install zsh if not present (should be on macOS)
          which zsh || brew install zsh

          # Run benchmark
          echo "### Zsh Startup Benchmark"
          hyperfine --warmup 3 --runs 10 'zsh -i -c exit' || true

      - name: Check for common issues
        run: |
          echo "Checking for potential secrets..."
          ! grep -r "password\|secret\|token" --include="*.tmpl" --exclude-dir=".git" . || echo "Warning: Potential secrets found in templates"

          echo "Checking for shell syntax errors..."
          find . -name "*.sh" -o -name "*.zsh" | while read file; do
            echo "Checking $file"
            zsh -n "$file" 2>&1 || echo "Syntax error in $file"
          done

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
        continue-on-error: true

      - name: Validate markdown formatting
        run: |
          echo "Checking markdown files..."
          find docs -name "*.md" -exec echo "✓ {}" \;
